### vulnerability database Configuration Settings
---

sator:

### Toggle application level debug (does not toggle framework debugging)
  debug: true

### Where external (third-party) plugins are loaded from
  plugin_dir: /var/lib/sator/plugins/

### Where all plugin configurations are loaded from
  plugin_config_dir: /etc/sator/plugins.d/

### Where external templates are loaded from
# template_dir: /var/lib/sator/templates/

### The log handler label
  log_handler: colorlog
  working_dir: ~/projects/sator

### Threading
  local_threads: 8

### The output handler label
# output_handler: jinja2

flask:
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  CSRF_ENABLED: true
  SECRET_KEY: "SECRET_KEY"
  SQLALCHEMY_DATABASE_URI: postgresql://user1:user123@localhost:5432/sator
  RUN_PORT: 3001
  DEBUG: false


log.colorlog:

### Where the log file lives (no log file by default)
  file: /tmp/sator.logs

### The level for which to log.  One of: info, warning, error, fatal, debug
  level: info

### Whether or not to log to console
  to_console: true

### Whether or not to rotate the log file when it reaches `max_bytes`
  rotate: true

### Max size in bytes that a log file can grow until it is rotated.
  max_bytes: 512000

### The maximum number of log files to maintain when rotating
  max_files: 4
